---
# file: roles/master-init/tasks/main.yml

- name: hdfs namenode format check 
  command: ls /data/1/dfs/nn/current
  register: hdfs_format
  failed_when: hdfs_format.rc not in [0,1,2]
  changed_when: hdfs_format.rc not in [0,1]
  notify: hdfs namenode format

- name: master service settings
  service: name={{item}} state=started enabled=yes
  with_items:
    - hadoop-hdfs-namenode
    - hadoop-hdfs-secondarynamenode
    - hadoop-yarn-resourcemanager
    - hadoop-mapreduce-historyserver
