---
# file: roles/common-setup/tasks/main.yml

- name: copy hadoop-conf
  file: dest=/etc/hadoop/{{hadoop_conf}} state=directory

- name: create hadoop-setting
  template: src={{item}}.j2 dest=/etc/hadoop/{{hadoop_conf}}/{{item}}
  with_items:
    - capacity-scheduler.xml
    - configuration.xsl
    - container-executor.cfg
    - core-site.xml
    - hadoop-metrics.properties
    - hadoop-metrics2.properties
    - hadoop-policy.xml
    - hdfs-site.xml
    - log4j.properties
    - mapred-queues.xml.template
    - mapred-site.xml
    - mapred-site.xml.template
    - slaves
    - ssl-client.xml.example
    - ssl-server.xml.example
    - yarn-env.sh
    - yarn-site.xml
