---
# file: roles/common-setup/tasks/main.yml

- name: copy hadoop-conf
  file: dest=/etc/hadoop/{{hadoop_conf}} state=directory

- name: create hadoop-setting
  template: src={{item}}.j2 dest=/etc/hadoop/{{hadoop_conf}}/{{item}}
  with_items:
    - capacity-scheduler.xml
    - configuration.xsl
    - container-executor.cfg
    - core-site.xml
    - hadoop-metrics.properties
    - hadoop-metrics2.properties
    - hadoop-policy.xml
    - hdfs-site.xml
    - log4j.properties
    - mapred-queues.xml.template
    - mapred-site.xml
    - mapred-site.xml.template
    - slaves
    - ssl-client.xml.example
    - ssl-server.xml.example
    - yarn-env.sh
    - yarn-site.xml

- name: hadoop-conf check
  shell: alternatives --display hadoop-conf | grep Current | sed 's#[^/]*\(/.*\)\.$#\1#'
  register: alter_hadoop_conf
  failed_when: alter_hadoop_conf.rc not in [0,1]
  changed_when: alter_hadoop_conf.stdout.find('/etc/hadoop/{{hadoop_conf}}') == -1

- name: alternatives hadoop-conf
  alternatives: name=hadoop_conf link=/etc/hadoop/conf path=/etc/hadoop/{{hadoop_conf}}
  when: alter_hadoop_conf.stdout.find('/etc/hadoop/{{hadoop_conf}}') == -1

- name: add bash settings for hadoop-hdfs
  template: src=dot_{{item}}.j2 dest=/var/lib//hadoop-hdfs/.{{item}}
  with_items:
    - bash_logout
    - bash_profile
    - bashrc

- name: bash settings for hadoop-hdfs
  template: src=dot_{{item}}.j2 dest=/var/lib//hadoop-hdfs/.{{item}} owner=hdfs group=hdfs
  with_items:
    - bash_logout
    - bash_profile
    - bashrc

- name: bash settings for hadoop-mapreduce
  template: src=dot_{{item}}.j2 dest=/var/lib//hadoop-mapreduce/.{{item}} owner=mapred group=mapred
  with_items:
    - bash_logout
    - bash_profile
    - bashrc

- name: bash settings for hadoop-yarn
  template: src=dot_{{item}}.j2 dest=/var/lib//hadoop-yarn/.{{item}} owner=yarn group=yarn
  with_items:
    - bash_logout
    - bash_profile
    - bashrc
