---
# file: roles/common/handlers/main.yml
- name: ntpd start
  service: name=ntpd state=started enabled=yes

- name: restart ntpd
  service: name=ntpd state=restarted

- name: copy Oracle JDK
  copy: src={{jdk}} dest=/tmp

- name: Oracle JDK install
  yum: name=/tmp/{{jdk}} state=present
