---
# file: roles/slave/tasks/main.yml

- name: packages install
  yum: name={{item}} state=present
  with_items:
    - hadoop-yarn-nodemanager
    - hadoop-hdfs-datanode
    - hadoop-mapreduce

- name: create partition
  command: parted /dev/{{item.dev}} mklabel gpt -- mkpart primary ext4 1 -1
  when: ansible_devices.{{item.dev}}.partitions.{{item.dev}}1 is not defined
  with_items: hadoop_storage

- name: format for hdfs disk.
  filesystem: fstype=ext4 dev=/dev/{{item.dev}}1
  with_items: hadoop_storage

- name: mount device for hdfs
  mount: name={{item.mount_point}} src=/dev/{{item.dev}}1 fstype=ext4 state=mounted
  with_items: hadoop_storage

- name: create datanode dir
  file: dest={{item.mount_point}}/dfs/dn state=directory recurse=yes owner=hdfs group=hdfs mode=0700
  with_items: hadoop_storage

- name: create nodemanager dir
  file: dest={{item.mount_point}}/yarn/local state=directory recurse=yes owner=yarn group=hdfs mode=0755
  with_items: hadoop_storage

- name: create nodemanager log dir
  file: dest={{item.mount_point}}/yarn/logs state=directory recurse=yes owner=yarn group=hdfs mode=0755
  with_items: hadoop_storage
