---
# file: roles/common/tasks/main.yml

- name: packages install
  yum: name={{item}} state=present
  with_items:
    - openssh-clients
    - libselinux-python
    - ntp

- name: disable selinux
  selinux: state=disabled

- name: ntp setting
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
