---
# file: roles/master/tasks/main.yml

- name: packages install
  yum: name={{item}} state=present
  with_items:
    - hadoop-yarn-resourcemanager
    - hadoop-hdfs-namenode
    - hadoop-hdfs-secondarynamenode
    - hadoop-mapreduce-historyserver
    - hadoop-yarn-proxyserver

- name: create namenode dir
  file: dest={{item}}/dfs/nn state=directory recurse=yes owner=hdfs group=hdfs mode=0700
  with_items:
    - /data/1

- name: create secondary namenode dir
  file: dest={{item}}/dfs/snn state=directory recurse=yes owner=hdfs group=hdfs mode=0700
  with_items:
    - /data/1
